### ISSUE TITLE
Services: list, call, response

### ISSUE THREAD

**Issue by jhurliman** [foxglove/ros-foxglove-bridge#10]

**Comment by jhurliman** [comment]
An example implementation of calling ROS 2 services from a bridge can be found here: <https://github.com/v-kiniv/rws/blob/main/src/client_handler.cpp#L406-L450>. The method is straightforward, most of the work is in JSON<->CDR serde. We can avoid this by using our client binary serialization already used for topic publishing.

**Comment by jhurliman** [comment]
Based on the ROS 2 notes above, I think the bridge protocol for services could roughly look like this:

* op: `advertiseService` // server -> client
* op: `unadvertiseService` // server -> client
* op: `callService` // client -> server
* op: `serviceAcknowledgement` // server -> client
* op: `serviceResponse` // server -> client

**Comment by achim-k** [comment]
> * op: `serviceAcknowledgement` // server -> client

What is this for? Acknowledging a client's service call request?

**Comment by jhurliman** [comment]
Let's drop `serviceAcknowledgement`, but send an error back if the service is not running or there's another failure to initiate the service call.
