### ISSUE TITLE
Subscriptions not working on ROS2 rolling

### ISSUE THREAD

**Issue by achim-k** [foxglove/ros-foxglove-bridge#120]
**Description**

- Version: latest
- Platform: `ROS2 rolling / ubuntu jammy` (provided docker image)

**Steps To Reproduce**
1. Run the bridge e.g. with `docker run --pull --rm -it --name foxbridge --net=host ghcr.io/foxglove/rolling-ros2-bridge`
2. Publish a periodic topic e.g. `docker exec -it foxbridge bash -c "source /opt/ros/rolling/setup.bash && ros2 topic pub /foo std_msgs/String data:\ 'hello'"`
3. Connect a client and observe that subscriptions are not working
  - E.g. use Studio with a raw panel (https://studio.foxglove.dev/?ds=foxglove-websocket&ds.url=ws%3A%2F%2Flocalhost%3A8765)

**Expected Behavior**
Client should receive messages of subscribed channels

**Comment by defunctzombie** [comment]
https://linear.app/foxglove/issue/FG-1034/subscriptions-not-working-on-ros2-rolling-[foxgloveros-foxglove-bridge

Don't know why the bot did not comment on this.

**Comment by achim-k** [comment]
Observation: Making a graph change by e.g. publishing on a random topic (ros2 topic pub /asdf std_msgs/String data:\ "meh") triggers the bridge to send messages to the client :thinking:

**Comment by achim-k** [comment]
Underlying rclcpp issue: https://github.com/ros2/rclcpp/issues/2067
