### ISSUE TITLE
ros1 docker image is broken

### ISSUE THREAD

**Issue by jhurliman** [foxglove/ros-foxglove-bridge#150]
```
$ docker run --rm -it -v /opt/ros:/opt/ros --net=host ghcr.io/foxglove/noetic-ros1-bridge
/ros_entrypoint.sh: line 5: /opt/ros/noetic/setup.bash: No such file or directory
```

**Comment by achim-k** [comment]
This happens when you don't have a local ros installation (`/opt/ros/...`). Leaving out the  `-v /opt/ros:/opt/ros` makes it work. It's the same for #149

I think we should consider removing documentation for the docker images. They offer little value as they don't work with custom types.

**Comment by defunctzombie** [comment]
I second getting rid of these images. I do not think they fall into a typical ROS workflow. It is not worth the time to maintain and fix them.
