### ISSUE TITLE
Docs are a little sparse on configuration

### ISSUE THREAD

**Issue by rgov** [foxglove/ros-foxglove-bridge#157]
https://foxglove.dev/docs/studio/connection/using-foxglove-bridge - This page tells you how to install it and which config options it takes, but it doesn't have an example of how to launch it.

https://github.com/foxglove/ros-foxglove-bridge#running-the-bridge - explains how to launch it but doesn't show how to set configuration options on it.

For completeness it would be nice to have some examples like these, to spare the user having to look up the syntax roslaunch uses:

```
$ roslaunch foxglove_bridge foxglove_bridge.launch port:=1989 --screen
```

```xml
<launch>

    <!-- Including in another launch file --> 
    <include file="$(find foxglove_bridge)/launch/foxglove_bridge.launch">
        <arg name="port" value=1989 />
    </include>

</launch>
```

**Comment by rgov** [comment]
The `topic_whitelist` parameter is also a list which is a little weird to pass:

```
<arg name="topic_whitelist" value="[&quot;^(?!/camera/image$).*&quot;]" />
```

**Comment by achim-k** [comment]
> The `topic_whitelist` parameter is also a list which is a little weird to pass:
> 
> ```
> <arg name="topic_whitelist" value="[&quot;^(?!/camera/image$).*&quot;]" />
> ```

Agreed, it's not very intuitive.
Maybe the best for you would be to create your own version of `foxglove_bridge.launch` so you can use `<rosparam>`:

```xml
  ...
  <node pkg="nodelet" type="nodelet" name="foxglove_bridge"
        args="load foxglove_bridge/foxglove_bridge_nodelet $(arg nodelet_manager)">
    <rosparam>
      port: 8765
      topic_whitelist:
        - "^(?!/camera/image$).*"
    </rosparam>
  </node>
```
