### ISSUE TITLE
[ROS2] Custom types and parameters fail

### ISSUE THREAD

**Issue by bertaveira** [foxglove/ros-foxglove-bridge#164]
**Description**
Right now, we have a custom service type that we do not really care about. The problem is that the bridge tries to get it and since it does not recognise the type it throws errors on the terminal as well as warnings on the ros log. While this happens we lose messages for about 3 seconds until it comes back to life.

Log window:
<img width="619" alt="image" src="https://user-images.githubusercontent.com/9644729/219378901-f151568f-a861-4e4f-8674-cabf0b380b39.png">

- Version: Latest main
- Platform: Ubuntu 22.04 (ROS humble)

**Comment by bertaveira** [comment]
We tried adding the custom message but now the error is in retrieving the parameters and it still stops recieving for a few seconds 

<img width="833" alt="image" src="https://user-images.githubusercontent.com/9644729/219381389-846b2cfd-1686-4ac0-9d4b-6d75db36924d.png">

**Comment by achim-k** [comment]
There should not be a delay services / parameters could not be retrieved. I will look into this.

For the short term, you may want to whitelist only the services / parameters that you are interested in
