### ISSUE TITLE
[ROS2] Failed to parse channel schema

### ISSUE THREAD

**Issue by bertaveira** [foxglove/ros-foxglove-bridge#171]
Hi! 

We just updated to the newest version of the Ros Foxglove Bridge (commit 8f327d1) and are experiencing issues reading topics. It worked fine on the version we were using previously.

Most of the topics are common schemes such as Float32 and Float64 etc. See image below:
![image](https://user-images.githubusercontent.com/9644729/220189795-b88f97d2-7646-4e4c-b747-e4d852e1ea1e.png)

Pressing one of the errors gives the following output, this is a Float64 message:
![image](https://user-images.githubusercontent.com/9644729/220189875-e230b336-ba66-4968-ada9-789a66b5a843.png)

**Comment by achim-k** [comment]
@bertaveira is this still an issue for you?

**Comment by achim-k** [comment]
Closing this for now. @bertaveira feel free to re-open if the problem persists.
