### ISSUE TITLE
[Foxglove Nodelet Manager] process had died

### ISSUE THREAD

**Issue by joewong00** [foxglove/ros-foxglove-bridge#220]
**Description**
Everything is working fine until I launch **robot localization** node package, then foxglove throws the error "terminate called after throwing an instance of 'XmlRpc::XmlRpcException'.

- Version: 0.5.1
- Platform: Jetson Xavier NX with ROS Melodic, M1 macos for foxglove client

**Steps To Reproduce**

1. Launch foxglove bridge: `roslaunch foxglove_bridge foxglove_bridge.launch port:=8765`
2. Launch robot localization node with preset parameters: `roslaunch robot_localization robot_localization.launch`
3. Establish connection from foxglove studio on client side

**Expected Behavior**
- Able to establish connection without any issue

**Comment by defunctzombie** [comment]
Please provide the ROS version and the `foxglove_bridge` version.

**Comment by joewong00** [comment]
ROS version: ROS melodic
Foxglove bridge version: 0.5.1

**Comment by joewong00** [comment]
After some more digging into this issue, I realised that the error has nothing to do with the robot localization package itself, but instead the loading of the parameters, in my case the array parameters of process noise covariance and initial estimate covariance. How do I fix this?

**Comment by defunctzombie** [comment]
This issue has already been fixed in the latest code: https://github.com/foxglove/ros-foxglove-bridge/pull/218.

ROS melodic is EOL and I don't think will get any more package updates. I recommend you build this package from source in your ROS workspace if you want to keep using melodic.
