### ISSUE TITLE
report err when my node running

### ISSUE THREAD

**Issue by sgf201** [foxglove/ros-foxglove-bridge#236]
**Description**
![image](https://github.com/foxglove/ros-foxglove-bridge/assets/5253415/e7228721-6acf-48b5-ab71-662935f218c0)

- Version:
- Platform:

**Steps To Reproduce**

there are large msg transmit when err occur

**Expected Behavior**
do not report err

**Comment by achim-k** [comment]
Does `ros2 param list `/camera_node` fail as well?

If you do not use Foxglove Studio's parameter panel, you can disable the [`parameters` and `parametersSubscribe`](https://github.com/foxglove/ros-foxglove-bridge/blob/29ac3989383dc9f2e1d6862c73738422a87d8736/ros2_foxglove_bridge/launch/foxglove_bridge_launch.xml#L16) capabilities. This will prevent these error messages from being displayed.

**Comment by achim-k** [comment]
> Does `ros2 param list /camera_node` fail as well?

@sgf201 does this fail as well? Do you still have this issue?

**Comment by sgf201** [comment]
the test board is not usable now, I will report after test

**Comment by achim-k** [comment]
I'm going to close this issue. @sgf201 feel free to reopen this issue with detailed reproduction steps and the foxglove bridge version.
