### ISSUE TITLE
ROS 1 latched topics

### ISSUE THREAD

**Issue by jhurliman** [foxglove/ros-foxglove-bridge#30]
To make topics like `/tf_static` work, latching semantics must be carried through the bridge. Upon subscribing to a latched topic, the most recent message must be held in memory and sent when a client subscribes to the latched channel.

**Comment by achim-k** [comment]
We will have to make changes to the websocket server implementation for that. Currently it does not support to send messages to individual clients. In case a client subscribes to a latched topic, we only want to send the latest message to that client. All other subscribed clients should not re-receive the latest message.
