### ISSUE TITLE
Invalid service definition

### ISSUE THREAD

**Issue by tonynajjar** [foxglove/ros-foxglove-bridge#301]
**Description**

- Version of foxglove bridge: 0.7.7
- Platform: foxglove studio 2.6.0

**Steps To Reproduce**

```
[foxglove_bridge-22] [WARN] [1718109515.363661001] [foxglove_bridge]: Failed to add service /perception/front_left/device_info;(realsense2_camera_msgs/srv/DeviceInfo): Invalid service definition in DeviceInfo.srv: Expected 2 definitions, got 1
```

The srv seems reasonable https://github.com/IntelRealSense/realsense-ros/blob/ros2-development/realsense2_camera_msgs/srv/DeviceInfo.srv

**Comment by achim-k** [comment]
Yeah, that's strange. I will take a look, thanks for reporting

**Comment by tonynajjar** [comment]
I'm on Humble. I'm reverting your commit and checking if it reproduces

**Comment by tonynajjar** [comment]
confirmed, checked out the commit before the PR I linked (hash 3e35af32fde80dc42e6c7bea40a2cc32c30170f4) and the issue does not reproduce

**Comment by achim-k** [comment]
The reason is an additional CR `0x0D` before the actual line feed `0x0A` at the end of the line :sob: Will push a fix in a couple of hours.

![image](https://github.com/foxglove/ros-foxglove-bridge/assets/9250155/346eaeaa-1923-4592-9b8e-b06d57fa3585)

**Comment by tonynajjar** [comment]
It's impressive how fast you figured out such a hidden issue :laughing: Let me know when you have the fix, I might be still in time to give it a quick test
