### ISSUE TITLE
ROS 2 "latched" topics

### ISSUE THREAD

**Issue by jhurliman** [foxglove/ros-foxglove-bridge#31]
To make topics like `/tf_static` work, transient-local semantics must be carried through the bridge. Upon subscribing to a topic with one or more transient-local publishers, transient-local should be enabled, and the depth should equal the max depth of the set of transient-local publishers. An in-memory buffer of size `depth` should hold the latest messages, and all of those messages sent to new subscribers.

**Comment by achim-k** [comment]
For every transient-local publisher of a topic, we should store the last `depth` messages in memory. However, I think this can be tricky as the publisher ID is currently not forwarded to [rclcpp::GenericSubscription](https://github.com/ros2/rclcpp/blob/91bc312190e61c8915b0152e5c927c987fc22d6c/rclcpp/src/rclcpp/generic_subscription.cpp#L47-L52)'s callback (which we currently use for subscriptions). So it seems that there is no way to tell from which publisher a message originates.
