### ISSUE TITLE
OMG IDE support missing?

### ISSUE THREAD

**Issue by eyr1n** [foxglove/ros-foxglove-bridge#312]
**Description**

Why is OMG IDE support missing since PR #293?

It seems to me that support is still needed for OMG IDL style interfaces because they can represent things that cannot be represented in ROS 2 IDL (e.g. sequence<T, N> type).

- Version: 0.7.7
- Platform: ROS 2 Humble w/ Ubuntu 22.04

**Comment by achim-k** [comment]
This was not intended, will be fixed next week.

**Comment by achim-k** [comment]
@eyr1n could you give #313 a try and check if it fixes the issue?
