### ISSUE TITLE
Changing of gradient and min-max scaling value doesn't change the visualization result

### ISSUE THREAD

**Issue by TharitSinsunthorn** [foxglove/ros-foxglove-bridge#323]
**Description**
I have set the panel for visualizing the depth camera topic from Isaacsim, using ros2 foxglove bridge. However, when I tried to change the gradient color and also scaling value range, there is no change in the visualization panel.

![Screenshot from 2024-09-02 17-44-54](https://github.com/user-attachments/assets/2578689c-3539-45b5-8bf4-01efa2e57794)

**Expectation**
I also tested in rviz and the expected result should show the image from depth camera more clear

![Screenshot from 2024-09-02 17-45-46](https://github.com/user-attachments/assets/5e0903c5-96f4-4850-ba57-478332c9f064)

Here is the reference from RGB image

![Screenshot from 2024-09-02 17-49-14](https://github.com/user-attachments/assets/a30af005-967e-49b2-b948-79c91a4359f3)

**Comment by achim-k** [comment]
This issue does not seem related to foxglove bridge but rather to the Foxglove app. Could you open the bug report either at https://github.com/orgs/foxglove/discussions or ask for support on [Discord](https://foxglove.dev/chat)? I'm going to close this issue.

**Comment by TharitSinsunthorn** [comment]
OK, sorry for confusing
