### ISSUE TITLE
The video streaming picture is incomplete

### ISSUE THREAD

**Issue by zerosnsa** [foxglove/ros-foxglove-bridge#325]
I ran the rosnoetic version on the Ubuntu22.04 version on jetson orin nano. Using this case, the image of the video stream pulled from the Windows software is incomplete. May I ask what happened and how can I solve it?
![8986fc437f1bc8fe0f90b055eec8692](https://github.com/user-attachments/assets/1ce64e80-f9fc-4e5a-8211-42d8484251c0)

**Comment by zerosnsa** [comment]
![image](https://github.com/user-attachments/assets/257a00a4-5781-4a5c-8622-0c85bf2eaf74)
I don't have access

**Comment by jtbandes** [comment]
It looks like your image is curved because of camera distortion parameters. Can you describe what is unexpected about this?

**Comment by defunctzombie** [comment]
@zerosnsa this looks like it works as designed and is using the camera parameters to display the image. If you have additional notes on why that behavior is not as expected please share and we can re-visit this.
