### ISSUE TITLE
Publish docker images for ROS 1 + ROS 2 nodes

### ISSUE THREAD

**Issue by jhurliman** [foxglove/ros-foxglove-bridge#42]
One method of releasing binaries ahead of the ROS .deb release schedule is via Docker publishing. While this workflow doesn't support everyone's needs, there is [enough](https://github.com/labellson/docker-rosbridge) [community](https://github.com/JoaquinGimenez1/docker-noetic-rosbridge) [interest](https://hub.docker.com/r/labellson/rosbridge) [in](https://answers.ros.org/question/343814/rosbridge-in-docker-unable-to-load-the-manifest-for-package/) Docker images that I think it merits the extra one-time investment in setting it up.

**Comment by defunctzombie** [comment]
My general take on this is that it isn't the typical mode of using a package in ROS. Some of the items linked are stale and none of them point to that much interest. Its true you can do this - but is anyone that we want testing this today asking for this mode of packaging or will they run from source builds?
