### ISSUE TITLE
Bridge not compatible with ROS2 actions

### ISSUE THREAD

**Issue by ccpowers** [foxglove/ros-foxglove-bridge#60]
When launching the foxglove bridge in ROS2, it will crash if an action server is present.

- Version: latest
- Platform: ubuntu jammy, ros2 humble

**Steps To Reproduce**
1. Launch the getting started example for Nav2: https://navigation.ros.org/getting_started/index.html#running-the-example
Specifically, the following:
```
export TURTLEBOT3_MODEL=waffle
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/opt/ros/<ros2-distro>/share/turtlebot3_gazebo/models
ros2 launch nav2_bringup tb3_simulation_launch.py headless:=False
```
Alternately, you can probably reproduce by launching anything that has an action server or client. 

2. Run the foxglove bridge:
```
ros2 run foxglove_bridge foxglove_bridge
```
The bridge will exit with an error (described below). 

**Expected Behavior**
Bridge launches.

**Actual Behavior**
Bridge crashes with error:
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Invalid package resource name: nav2_msgs/action/NavigateThroughPoses_FeedbackMessage
```

**Comment by achim-k** [comment]
This seems to be a consequence of #58
