### ISSUE TITLE
Subscription smoke test is failing on Rolling Jammy in ROS buildfarm

### ISSUE THREAD

**Issue by jhurliman** [foxglove/ros-foxglove-bridge#94]
See <https://build.ros2.org/job/Rdev__foxglove_bridge__ubuntu_jammy_amd64/21/>.

Connection and publishing tests are working, but no messages are received in the subscription test (this is different from the callback_group issue since no message is ever received). This test is passing for Humble Jammy; see <https://build.ros2.org/job/Hdev__foxglove_bridge__ubuntu_jammy_amd64/9/>.

```
2: [ RUN      ] SmokeTest.testSubscription
2: [INFO] [1669838650.865567189] [foxglove_bridge]: [WS] Client 127.0.0.1:43488 connected via /
2: [INFO] [1669838651.349482682] [foxglove_bridge]: Subscribing to topic "/pub_topic" (std_msgs/msg/String) on channel 3
2: /tmp/ws/src/foxglove_bridge/ros2_foxglove_bridge/tests/smoke_test.cpp:76: Failure
2: Expected equality of these values:
2:   std::future_status::ready
2:     Which is: 4-byte object <00-00 00-00>
2:   msgFuture.wait_for(std::chrono::seconds(5))
2:     Which is: 4-byte object <01-00 00-00>
2: [INFO] [1669838656.349140779] [foxglove_bridge]: [WS] Client 127.0.0.1:43488 disconnected
2: [INFO] [1669838656.350879868] [foxglove_bridge]: Unsubscribing from topic "/pub_topic" (std_msgs/msg/String) on channel 3
2: [  FAILED  ] SmokeTest.testSubscription (5502 ms)
```

**Comment by achim-k** [comment]
It looks like the test even crashed for the previous runs:

- https://build.ros2.org/job/Rdev__foxglove_bridge__ubuntu_jammy_amd64/20/testReport/(root)/projectroot/smoke_test/
- https://build.ros2.org/job/Rdev__foxglove_bridge__ubuntu_jammy_amd64/19/testReport/(root)/projectroot/smoke_test/

**Comment by achim-k** [comment]
Very likely related to #120
